version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: aslam
      MONGO_INITDB_ROOT_PASSWORD: aslam_pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: aslam
      ME_CONFIG_MONGODB_ADMINPASSWORD: aslam_pass
      ME_CONFIG_MONGODB_URL: mongodb://aslam:aslam_pass@mongo:27017/
